---
- name: Example of password-in-command rule
  hosts: localhost
  tasks: 
    - name: Run arbitrary command with passwords
      ansible.builtin.command:
        cmd: /usr/bin/runprocess.sh db_user {{ password }}
        creates: /path/to/output
        no_log: true
    - name: Run arbitrary command with passwords
      ansible.builtin.command:
        cmd: /usr/bin/runprocess.sh user=dbuser pwd=dbpwd
        creates: /path/to/output
        no_log: true
    - name: Run arbitrary command with passwords
      ansible.builtin.command:
        cmd: /usr/bin/runprocess.sh -user db_user -pass {{ my_secret }}
        creates: /path/to/output
        no_log: true
# The following tasks use inline command format, and do
# not specify the no_log param at all (which will default to false)
    - name: Run arbitrary command with passwords
      ansible.builtin.command: /usr/bin/runprocess.sh db_user {{ password }}
      args:
        creates: /path/to/output
        no_log: true
    - name: Run arbitrary command with passwords
      ansible.builtin.command: /usr/bin/runprocess.sh user=dbuser pwd=dbpwd
      args:
        creates: /path/to/output
        no_log: true
    - name: Run arbitrary command with passwords
      ansible.builtin.command: /usr/bin/runprocess.sh -user db_user -pass {{ my_secret }}
      args:
        creates: /path/to/output
        no_log: true