---
- name: Example of password-in-command rule
  hosts: localhost
  tasks:
    - name: Run arbitrary command with passwords
      ansible.builtin.command:
        cmd: /usr/bin/run-process.sh db_user {{ password }}
        creates: /path/to/output
        no_log: false
    - name: Run arbitrary command with passwords
      ansible.builtin.command:
        cmd: /usr/bin/run-process.sh user=db_user pwd=db_pwd
        creates: /path/to/output
        no_log: false
    - name: Run arbitrary command with passwords
      ansible.builtin.command:
        cmd: /usr/bin/run-process.sh -user db_user -pass {{ my_secret }}
        creates: /path/to/output
        no_log: false
    # The following tasks use inline command format, and do
    # not specify the no_log param at all (which will default to false)
    - name: Run arbitrary command with passwords
      ansible.builtin.command: /usr/bin/run-process.sh db_user {{ password }}
      args:
        creates: /path/to/output
    - name: Run arbitrary command with passwords
      ansible.builtin.command: /usr/bin/run-process.sh user=db_user pwd=db_pwd
      args:
        creates: /path/to/output
    - name: Run arbitrary command with passwords
      ansible.builtin.command: /usr/bin/run-process.sh -user db_user -pass {{ my_secret }}
      args:
        creates: /path/to/output
